language: node_js
node_js:
  - "12.9.0"
cache:
  directories:
    - node_modules
jobs:
  include:
    - stage: test
      script:
        - echo 'Installing Deps!'
        - npm install
        - npm run build
        - echo 'Testing!'
        - npm run test
    -stage: deploy
      script:
        - npm install -g firebase-tools
        - firebase deploy --token "$FIREBASE_TOKEN"
stages:
  - name: test
    # require the type to be a PR
    if: type = pull_request
  - name: deploy
    # require the type to be push to master
    if: type = push AND branch = master


